[build]
  base = "."
  publish = "frontend/build"
  command = "cd frontend && npm install --silent && npm run build-silent"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# API redirects (must come before catch-all)
[[redirects]]
  from = "/api/workloads"
  to = "/.netlify/functions/workloads"
  status = 200

[[redirects]]
  from = "/api/metrics"
  to = "/.netlify/functions/metrics"
  status = 200

[[redirects]]
  from = "/api/optimization"
  to = "/.netlify/functions/optimization"
  status = 200

[[redirects]]
  from = "/api/performance"
  to = "/.netlify/functions/performance"
  status = 200

[[redirects]]
  from = "/api/rag"
  to = "/.netlify/functions/rag"
  status = 200

[[redirects]]
  from = "/api/cost-analysis"
  to = "/.netlify/functions/cost-analysis"
  status = 200

[[redirects]]
  from = "/api/efficiency-analysis"
  to = "/.netlify/functions/efficiency-analysis"
  status = 200

[[redirects]]
  from = "/api/savings-summary"
  to = "/.netlify/functions/savings-summary"
  status = 200

# Catch-all redirect (must come last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"